DROP TABLE IF EXISTS t_comment;
DROP TABLE IF EXISTS t_user;
DROP TABLE IF EXISTS t_article;

CREATE TABLE t_article (
  art_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  art_title VARCHAR(100) NOT NULL,
  art_content VARCHAR(2000) NOT NULL
) ENGINE=innodb CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE t_user (
  usr_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  usr_name VARCHAR(50) NOT NULL,
  usr_password VARCHAR(88) NOT NULL,
  usr_salt VARCHAR(23) NOT NULL,
  usr_role VARCHAR(50) NOT NULL
) ENGINE=innodb CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE t_comment (
  com_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  com_content VARCHAR(500) NOT NULL,
  art_id INTEGER NOT NULL,
  usr_id INTEGER NOT NULL,
  CONSTRAINT fk_com_art FOREIGN KEY(art_id) REFERENCES t_article(art_id),
  CONSTRAINT fk_com_usr FOREIGN KEY(usr_id) REFERENCES t_user(usr_id)
) ENGINE=innodb CHARACTER SET utf8 COLLATE utf8_unicode_ci;